// <auto-generated />
using System;
using BSC20925_76122_Resit.Web.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BSC20925_76122_Resit.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260708234901_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.20");

            modelBuilder.Entity("BSC20925_76122_Resit.Web.Models.InsuranceClaim", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("ClaimDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimReference")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimStatus")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("Submitted");

                    b.Property<string>("ClaimType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.Property<string>("CreatedBy")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("System");

                    b.Property<string>("CustomerEmail")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("EstimatedAmount")
                        .HasPrecision(18, 2)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("IncidentDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PolicyNumber")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT")
                        .HasDefaultValueSql("CURRENT_TIMESTAMP");

                    b.HasKey("Id");

                    b.HasIndex("ClaimReference")
                        .IsUnique();

                    b.HasIndex("ClaimStatus");

                    b.HasIndex("ClaimType");

                    b.HasIndex("CustomerName");

                    b.HasIndex("PolicyNumber");

                    b.ToTable("InsuranceClaims");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ClaimDate = new DateTime(2026, 7, 1, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClaimReference = "CLM-1001",
                            ClaimStatus = "Submitted",
                            ClaimType = "Motor",
                            CreatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9000),
                            CreatedBy = "System",
                            CustomerEmail = "mary@example.com",
                            CustomerName = "Mary O'Brien",
                            Description = "Rear bumper damaged in minor accident",
                            EstimatedAmount = 1250.00m,
                            IncidentDate = new DateTime(2026, 6, 28, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "POL-45678",
                            UpdatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9000)
                        },
                        new
                        {
                            Id = 2,
                            ClaimDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClaimReference = "CLM-1002",
                            ClaimStatus = "Under Review",
                            ClaimType = "Home",
                            CreatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9000),
                            CreatedBy = "System",
                            CustomerEmail = "john@example.com",
                            CustomerName = "John Smith",
                            Description = "Water damage from burst pipe",
                            EstimatedAmount = 3500.00m,
                            IncidentDate = new DateTime(2026, 6, 30, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "POL-12345",
                            UpdatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9010)
                        },
                        new
                        {
                            Id = 3,
                            ClaimDate = new DateTime(2026, 7, 3, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClaimReference = "CLM-1003",
                            ClaimStatus = "Approved",
                            ClaimType = "Health",
                            CreatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9010),
                            CreatedBy = "System",
                            CustomerEmail = "sarah@example.com",
                            CustomerName = "Sarah Johnson",
                            Description = "Hospital stay for surgery",
                            EstimatedAmount = 5000.00m,
                            IncidentDate = new DateTime(2026, 6, 25, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "POL-78901",
                            UpdatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9010)
                        },
                        new
                        {
                            Id = 4,
                            ClaimDate = new DateTime(2026, 7, 4, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            ClaimReference = "CLM-1004",
                            ClaimStatus = "Rejected",
                            ClaimType = "Travel",
                            CreatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9020),
                            CreatedBy = "System",
                            CustomerEmail = "michael@example.com",
                            CustomerName = "Michael Brown",
                            Description = "Lost luggage during international flight",
                            EstimatedAmount = 750.00m,
                            IncidentDate = new DateTime(2026, 7, 2, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            PolicyNumber = "POL-24680",
                            UpdatedAt = new DateTime(2026, 7, 8, 23, 49, 1, 20, DateTimeKind.Utc).AddTicks(9020)
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
